✅ Started W&B orchestrator run: orchestrator_20250620_185854
✅ Set MLflow experiment to: 'MLOps-Group-Project-Experiment'
▶️  Running step: 'data_load'...
2025/06/20 18:58:57 INFO mlflow.utils.conda: Conda environment mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 already exists.
2025/06/20 18:58:57 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpehpv9hlq for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 18:58:57 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 1>&2 && python3 run.py' in run with ID 'abcb6f72c700464fb002158b743e6787' ===
2025/06/20 18:59:21 INFO mlflow.projects: === Run (ID 'abcb6f72c700464fb002158b743e6787') succeeded ===
✅ Step 'data_load' finished.
▶️  Running step: 'data_validation'...
2025/06/20 18:59:22 INFO mlflow.utils.conda: Conda environment mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 already exists.
2025/06/20 18:59:22 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpi312lj0z for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 18:59:22 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 1>&2 && python3 run.py' in run with ID 'eba82f8e546b41449238ed7ee403d6f2' ===
2025/06/20 18:59:28 INFO mlflow.projects: === Run (ID 'eba82f8e546b41449238ed7ee403d6f2') succeeded ===
✅ Step 'data_validation' finished.
▶️  Running step: 'features'...
2025/06/20 18:59:29 INFO mlflow.utils.conda: Conda environment mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 already exists.
2025/06/20 18:59:29 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmp_oab4bfm for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 18:59:29 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 1>&2 && python run.py' in run with ID '832ffdb6aff044b48f82b895efee32b4' ===
2025/06/20 18:59:35 INFO mlflow.projects: === Run (ID '832ffdb6aff044b48f82b895efee32b4') succeeded ===
✅ Step 'features' finished.
▶️  Running step: 'preproccess'...
2025/06/20 18:59:36 INFO mlflow.utils.conda: Conda environment mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 already exists.
2025/06/20 18:59:36 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpuyithpem for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 18:59:36 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 1>&2 && python run.py' in run with ID '08605edc5cd545629c15cdbdc48c065b' ===
Error executing job with overrides: []
Traceback (most recent call last):
  File "/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/main.py", line 119, in main
    mlflow.run(step_dir, "main", parameters=params)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/projects/__init__.py", line 374, in run
    _wait_for(submitted_run_obj)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/projects/__init__.py", line 391, in _wait_for
    raise ExecutionException(f"Run (ID '{run_id}') failed")
mlflow.exceptions.ExecutionException: Run (ID '08605edc5cd545629c15cdbdc48c065b') failed

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
