✅ Started W&B orchestrator run: orchestrator_20250620_190243
✅ Set MLflow experiment to: 'MLOps-Group-Project-Experiment'
▶️  Running step: 'data_load'...
2025/06/20 19:02:45 INFO mlflow.utils.conda: === Creating conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 ===
2025/06/20 19:03:13 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpakthgaoy for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:03:13 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 run.py' in run with ID '58a5b2a6fe804c3cb978d7bb3467de61' ===
2025/06/20 19:03:40 INFO mlflow.projects: === Run (ID '58a5b2a6fe804c3cb978d7bb3467de61') succeeded ===
✅ Step 'data_load' finished.
▶️  Running step: 'data_validation'...
2025/06/20 19:03:41 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 19:03:41 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpfxs0heez for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:03:41 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python3 run.py' in run with ID '8ef772984474497aaab52ce5520b2baa' ===
2025/06/20 19:03:47 INFO mlflow.projects: === Run (ID '8ef772984474497aaab52ce5520b2baa') succeeded ===
✅ Step 'data_validation' finished.
▶️  Running step: 'features'...
2025/06/20 19:03:48 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 19:03:48 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpnfwkn06r for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:03:48 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python run.py' in run with ID '0756853e6f2a43ce85bb295509a60116' ===
2025/06/20 19:03:59 INFO mlflow.projects: === Run (ID '0756853e6f2a43ce85bb295509a60116') succeeded ===
✅ Step 'features' finished.
▶️  Running step: 'preproccess'...
2025/06/20 19:04:00 INFO mlflow.utils.conda: Conda environment mlflow-b38cc610a566358f4ff450976fe6275733f34b85 already exists.
2025/06/20 19:04:00 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpj_n7bi8t for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 19:04:00 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-b38cc610a566358f4ff450976fe6275733f34b85 1>&2 && python run.py' in run with ID '2f042e7e8a9f4567972a9a7a8cb1b578' ===
Error executing job with overrides: []
Traceback (most recent call last):
  File "/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/main.py", line 119, in main
    mlflow.run(step_dir, "main", parameters=params)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/projects/__init__.py", line 374, in run
    _wait_for(submitted_run_obj)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/projects/__init__.py", line 391, in _wait_for
    raise ExecutionException(f"Run (ID '{run_id}') failed")
mlflow.exceptions.ExecutionException: Run (ID '2f042e7e8a9f4567972a9a7a8cb1b578') failed

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
