✅ Started W&B orchestrator run: orchestrator_20250620_185720
✅ Set MLflow experiment to: 'MLOps-Group-Project-Experiment'
▶️  Running step: 'data_load'...
2025/06/20 18:57:23 INFO mlflow.utils.conda: Conda environment mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 already exists.
2025/06/20 18:57:23 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmp1acp1y7v for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 18:57:23 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 1>&2 && python3 run.py' in run with ID '75d5d6eb245141ca923469f225e54f0c' ===
2025/06/20 18:57:47 INFO mlflow.projects: === Run (ID '75d5d6eb245141ca923469f225e54f0c') succeeded ===
✅ Step 'data_load' finished.
▶️  Running step: 'data_validation'...
2025/06/20 18:57:48 INFO mlflow.utils.conda: Conda environment mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 already exists.
2025/06/20 18:57:48 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpm2nmzhv5 for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 18:57:48 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 1>&2 && python3 run.py' in run with ID '477c607e4c01489f9922a551b301ab48' ===
2025/06/20 18:57:53 INFO mlflow.projects: === Run (ID '477c607e4c01489f9922a551b301ab48') succeeded ===
✅ Step 'data_validation' finished.
▶️  Running step: 'features'...
2025/06/20 18:57:54 INFO mlflow.utils.conda: Conda environment mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 already exists.
2025/06/20 18:57:54 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpcxumfmoz for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 18:57:54 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 1>&2 && python run.py' in run with ID '99506f61f8774081831a19bff6294fe3' ===
2025/06/20 18:58:02 INFO mlflow.projects: === Run (ID '99506f61f8774081831a19bff6294fe3') succeeded ===
✅ Step 'features' finished.
▶️  Running step: 'preproccess'...
2025/06/20 18:58:03 INFO mlflow.utils.conda: Conda environment mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 already exists.
2025/06/20 18:58:03 INFO mlflow.projects.utils: === Created directory /var/folders/8m/nc66qdpd59zc9q76n8rk5d9m0000gn/T/tmpdnd8_2u6 for downloading remote URIs passed to arguments of type 'path' ===
2025/06/20 18:58:03 INFO mlflow.projects.backend.local: === Running command 'source /Users/aviv/Applications/anaconda3/bin/../etc/profile.d/conda.sh && conda activate mlflow-01d7074db45377d5418a7d608ce23d27d85b5d74 1>&2 && python run.py' in run with ID '4dc072d94e754318a3bc1dd6f10f8cf1' ===
Error executing job with overrides: []
Traceback (most recent call last):
  File "/Users/aviv/Library/Mobile Documents/com~apple~CloudDocs/study/MLOps_Group_Project/main.py", line 119, in main
    mlflow.run(step_dir, "main", parameters=params)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/projects/__init__.py", line 374, in run
    _wait_for(submitted_run_obj)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mlflow/projects/__init__.py", line 391, in _wait_for
    raise ExecutionException(f"Run (ID '{run_id}') failed")
mlflow.exceptions.ExecutionException: Run (ID '4dc072d94e754318a3bc1dd6f10f8cf1') failed

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
